name: shiling_fruit_garden
description: "基于气候区的水果采摘/种植指南 App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  sqflite: ^2.4.1
  sqflite_common_ffi: ^2.3.4+5
  path_provider: ^2.1.5
  shared_preferences: ^2.3.4
  intl: ^0.20.2
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/data/
    - assets/icons/fruits/
